default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lazeat_development

test:
  <<: *default
  database: lazeat_test



production:
  <<: *default
  database: lazeat_production
  username: lazeat
  password: <%= ENV['LAZEAT_DATABASE_PASSWORD'] %>
